# Generated by Django 5.0 on 2023-12-22 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('key_features', models.TextField()),
                ('technical_specifications', models.TextField()),
                ('technical_catalogue', models.URLField(blank=True)),
                ('user_manual', models.URLField(blank=True)),
                ('datasheet', models.URLField(blank=True)),
                ('image1', models.ImageField(upload_to='product_images/')),
                ('image2', models.ImageField(upload_to='product_images/')),
                ('image3', models.ImageField(upload_to='product_images/')),
                ('image4', models.ImageField(upload_to='product_images/')),
                ('image5', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(default=True, max_length=255, unique=True)),
                ('mobile_no', models.PositiveIntegerField(default=True, unique=True)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiecon.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Cartproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiecon.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiecon.product')),
            ],
        ),
    ]
