# Generated by Django 5.0 on 2023-12-25 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiecon', '0005_alter_customer_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiecon.product'),
        ),
    ]
