# Generated by Django 5.0 on 2024-03-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiecon', '0012_product_slug_alter_customer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
