# Generated by Django 5.0 on 2024-03-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiecon', '0014_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
