# Generated by Django 5.0.4 on 2024-04-26 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiecon', '0017_remove_product_price_product_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='Sku',
        ),
    ]
