# Generated by Django 5.0.4 on 2024-05-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiecon', '0018_rename_sku_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
